# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Luagame
repo_url: https://github.com/devbungfro/luagame
edit_uri: ""
site_url: https://luagame.bungfro.com/
repo_name: devbungfro/luagame

nav:
  - Home: index.md
  - Guide:
      - Installation: Guide/installation.md
      - Basic Example: Guide/basic_example.md

theme:
  name: material
  features:
    - content.code.annotate
  palette:
    scheme: slate
    primary: blue

  favicon: assets/icon.png

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.superfences
  - tables
  - admonition
  - pymdownx.inlinehilite
